### ISSUE TITLE
Errors leave fifo/pipes behind

### ISSUE THREAD

**Issue by Elither** [alexherbo2/kakoune.cr#11] opened 2021-03-15 16:09 UTC
Running many kcr commands in an incorrect way leaves behind a fifo/named pipe in the current directory. If not removed these can clutter and cause a mess. Would it be possible to instead place them in the /tmp folder where they would not be likely to cause issues and would eventually not require manual removal?

**Comment by alexherbo2** [comment] 2021-03-16 00:26
How can I reproduce?

FIFOs are normally generated using [`File.tempname`][`File`].

**Example**

``` sh
crystal eval 'puts File.tempname'
# /run/user/1000/20210316-20946-r2p2z2
```

[`File`]: https://crystal-lang.org/api/File.html

**Comment by Elither** [comment] 2021-03-16 12:57
Been playing with it more and whilst for me `crystal eval 'puts File.tempname'` usually correctly outputs something like `/tmp/20210316-11394-1qcbr4k`, for some reason, when run in a shell spawned by kakoune (kcr doesnt matter) `crystal eval 'puts File.tempname'` will simply output something like: `20210316-11762-78pds8` causing it to be created in the current directory. This actually breaks many kcr commands as if the shells current directory is different from kakounes then the pipe is opened and never written to as kakoune instead writes them to a new text file of the same name in its directory. 

So this is a problem of how shells spawned by kakoune handle it differently for some reason. I am unsure if this maybe something wrong with my configuration, although opening a kakoune session with no kakrc after renaming it and then initing kcr leads to the same problems.

**Comment by alexherbo2** [comment] 2021-03-16 13:33
To sum up, the culprit is [`tmux.kak`] which sets your [`TMPDIR`] to an empty value?

[`tmux.kak`]: https://github.com/mawww/kakoune/blob/master/rc/windowing/tmux.kak
[`TMPDIR`]: https://en.wikipedia.org/wiki/TMPDIR

**Comment by Elither** [comment] 2021-03-16 13:37
my TMPDIR is normally empty, but it didnt cause problems untill tmux.kak sets it to be nothing again and breaks it for some reason

**Comment by Elither** [comment] 2021-03-16 16:05
Ah, yes that seems to be what's happening, thanks.

**Comment by alexherbo2** [comment] 2021-03-16 16:45
Closing, as not a bug from kakoune.cr: it correctly honors the `TMPDIR` value.

**Closed by alexherbo2** 2021-03-16 16:45 UTC

**Comment by alexherbo2** [comment] 2021-04-22 23:24
@Elither Do you mind opening an issue upstream?  It looks @topisani has the same problem.

**Comment by Elither** [comment] 2021-04-24 13:20
https://github.com/mawww/kakoune/issues/4161
